services:
    app:
        build:
            context: .
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: ""
        ports:
            - "8000:80"

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
